const dishes = [
  // --- СУПЫ ---
  {
    keyword: "gazpacho",
    name: "Гаспачо",
    category: "soup",
    kind: "veg",
    sizes: { small: 150, medium: 200, large: 250 },
    image: "soups/gazpacho.jpg",
  },
  {
    keyword: "borsch",
    name: "Борщ",
    category: "soup",
    kind: "meat",
    sizes: { small: 180, medium: 230, large: 280 },
    image: "soups/borsch.jpg",
  },
  {
    keyword: "mushroom-soup",
    name: "Грибной суп",
    category: "soup",
    kind: "veg",
    sizes: { small: 160, medium: 210, large: 260 },
    image: "soups/mushroom.jpg",
  },
  {
    keyword: "chicken-soup",
    name: "Куриный суп",
    category: "soup",
    kind: "meat",
    sizes: { small: 170, medium: 220, large: 270 },
    image: "soups/chicken.jpg",
  },
  {
    keyword: "fish-soup",
    name: "Уха",
    category: "soup",
    kind: "fish",
    sizes: { small: 190, medium: 240, large: 290 },
    image: "soups/fish.jpg",
  },
  {
    keyword: "tomato-soup",
    name: "Томатный суп",
    category: "soup",
    kind: "veg",
    sizes: { small: 160, medium: 210, large: 260 },
    image: "soups/tomato.jpg",
  },

  // --- ГЛАВНЫЕ ---
  {
    keyword: "steak",
    name: "Стейк",
    category: "main",
    kind: "meat",
    sizes: { small: 450, medium: 520, large: 590 },
    image: "main/steak.jpg",
  },
  {
    keyword: "salmon",
    name: "Лосось на гриле",
    category: "main",
    kind: "fish",
    sizes: { small: 460, medium: 540, large: 620 },
    image: "main/salmon.jpg",
  },
  {
    keyword: "cutlet",
    name: "Котлета домашняя",
    category: "main",
    kind: "meat",
    sizes: { small: 300, medium: 360, large: 420 },
    image: "main/cutlet.jpg",
  },
  {
    keyword: "pasta",
    name: "Паста с овощами",
    category: "main",
    kind: "veg",
    sizes: { small: 250, medium: 310, large: 370 },
    image: "main/pasta.jpg",
  },
  {
    keyword: "rice",
    name: "Рис с грибами",
    category: "main",
    kind: "veg",
    sizes: { small: 220, medium: 280, large: 340 },
    image: "main/rice.jpg",
  },
  {
    keyword: "fish-fillets",
    name: "Филе рыбы",
    category: "main",
    kind: "fish",
    sizes: { small: 410, medium: 470, large: 530 },
    image: "main/fish.jpg",
  },

  // --- СТАРТЕРЫ / САЛАТЫ ---
  {
    keyword: "salad-greek",
    name: "Греческий салат",
    category: "starter",
    kind: "veg",
    sizes: { small: 180, medium: 230, large: 280 },
    image: "starters/greek.jpg",
  },
  {
    keyword: "salad-caesar",
    name: "Цезарь",
    category: "starter",
    kind: "meat",
    sizes: { small: 190, medium: 240, large: 290 },
    image: "starters/caesar.jpg",
  },
  {
    keyword: "salad-fish",
    name: "Салат с тунцом",
    category: "starter",
    kind: "fish",
    sizes: { small: 200, medium: 250, large: 300 },
    image: "starters/fish.jpg",
  },
  {
    keyword: "bruschetta",
    name: "Брускетта",
    category: "starter",
    kind: "veg",
    sizes: { small: 150, medium: 200, large: 250 },
    image: "starters/bruschetta.jpg",
  },
  {
    keyword: "salad-beet",
    name: "Свекольный салат",
    category: "starter",
    kind: "veg",
    sizes: { small: 140, medium: 190, large: 240 },
    image: "starters/beet.jpg",
  },
  {
    keyword: "salad-chicken",
    name: "Салат с курицей",
    category: "starter",
    kind: "meat",
    sizes: { small: 170, medium: 220, large: 270 },
    image: "starters/chicken.jpg",
  },

  // --- НАПИТКИ ---
  {
    keyword: "orange",
    name: "Апельсиновый сок",
    category: "drink",
    kind: "veg",
    sizes: { small: 90, medium: 120, large: 150 },
    image: "drinks/orange.jpg",
  },
  {
    keyword: "apple",
    name: "Яблочный сок",
    category: "drink",
    kind: "veg",
    sizes: { small: 90, medium: 120, large: 150 },
    image: "drinks/apple.jpg",
  },
  {
    keyword: "coffee",
    name: "Кофе",
    category: "drink",
    kind: "veg",
    sizes: { small: 100, medium: 130, large: 160 },
    image: "drinks/coffee.jpg",
  },
  {
    keyword: "tea",
    name: "Чай",
    category: "drink",
    kind: "veg",
    sizes: { small: 80, medium: 100, large: 120 },
    image: "drinks/tea.jpg",
  },
  {
    keyword: "carrot",
    name: "Морковный сок",
    category: "drink",
    kind: "veg",
    sizes: { small: 100, medium: 130, large: 160 },
    image: "drinks/carrot.jpg",
  },
  {
    keyword: "milkshake",
    name: "Молочный коктейль",
    category: "drink",
    kind: "veg",
    sizes: { small: 150, medium: 180, large: 210 },
    image: "drinks/milkshake.jpg",
  },
];
