const dishes = [
  // --- ГЛАВНЫЕ ---
  {
    keyword: "cutlet",
    name: "Котлета домашняя",
    category: "main",
    kind: "meat",
    sizes: { small: 300, medium: 360, large: 420 },
    image: "./images/meal/1.jpg",
  },
  {
    keyword: "salmon",
    name: "Лосось на гриле",
    category: "main",
    kind: "fish",
    sizes: { small: 460, medium: 540, large: 620 },
    image: "./images/meal/2.jpg",
  },

  {
    keyword: "pasta",
    name: "Паста с овощами",
    category: "main",
    kind: "veg",
    sizes: { small: 250, medium: 310, large: 370 },
    image: "./images/meal/3.jpg",
  },
  {
    keyword: "rice",
    name: "Рис с грибами",
    category: "main",
    kind: "veg",
    sizes: { small: 220, medium: 280, large: 340 },
    image: "./images/meal/4.jpg",
  },
  {
    keyword: "steak",
    name: "Стейк",
    category: "main",
    kind: "meat",
    sizes: { small: 450, medium: 520, large: 590 },
    image: "./images/meal/5.jpg",
  },
  {
    keyword: "fish-fillets",
    name: "Филе рыбы",
    category: "main",
    kind: "fish",
    sizes: { small: 410, medium: 470, large: 530 },
    image: "./images/meal/6.jpg",
  },
  // --- СУПЫ ---
  {
    keyword: "borsch",
    name: "Борщ",
    category: "soup",
    kind: "meat",
    sizes: { small: 180, medium: 230, large: 280 },
    image: "./images/soup/1.jpg",
  },
  {
    keyword: "gazpacho",
    name: "Гаспачо",
    category: "soup",
    kind: "veg",
    sizes: { small: 150, medium: 200, large: 250 },
    image: "./images/soup/2.jpg",
  },
  {
    keyword: "mushroom-soup",
    name: "Грибной суп",
    category: "soup",
    kind: "veg",
    sizes: { small: 160, medium: 210, large: 260 },
    image: "./images/soup/3.jpg",
  },
  {
    keyword: "chicken-soup",
    name: "Куриный суп",
    category: "soup",
    kind: "meat",
    sizes: { small: 170, medium: 220, large: 270 },
    image: "./images/soup/4.jpg",
  },
  {
    keyword: "tomato-soup",
    name: "Томатный суп",
    category: "soup",
    kind: "veg",
    sizes: { small: 160, medium: 210, large: 260 },
    image: "./images/soup/5.jpg",
  },
  {
    keyword: "fish-soup",
    name: "Уха",
    category: "soup",
    kind: "fish",
    sizes: { small: 190, medium: 240, large: 290 },
    image: "./images/soup/6.jpg",
  },

  // --- СТАРТЕРЫ / САЛАТЫ ---
  {
    keyword: "bruschetta",
    name: "Брускетта",
    category: "starter",
    kind: "veg",
    sizes: { small: 150, medium: 200, large: 250 },
    image: "./images/salad/1.jpg",
  },
  {
    keyword: "salad-greek",
    name: "Греческий салат",
    category: "starter",
    kind: "veg",
    sizes: { small: 180, medium: 230, large: 280 },
    image: "./images/salad/2.jpg",
  },
  {
    keyword: "salad-chicken",
    name: "Салат с курицей",
    category: "starter",
    kind: "meat",
    sizes: { small: 170, medium: 220, large: 270 },
    image: "./images/salad/3.jpg",
  },
  {
    keyword: "salad-fish",
    name: "Салат с тунцом",
    category: "starter",
    kind: "fish",
    sizes: { small: 200, medium: 250, large: 300 },
    image: "./images/salad/4.jpg",
  },
  {
    keyword: "salad-beet",
    name: "Свекольный салат",
    category: "starter",
    kind: "veg",
    sizes: { small: 140, medium: 190, large: 240 },
    image: "./images/salad/5.jpg",
  },
  {
    keyword: "salad-caesar",
    name: "Цезарь",
    category: "starter",
    kind: "meat",
    sizes: { small: 190, medium: 240, large: 290 },
    image: "./images/salad/6.jpg",
  },

  // --- НАПИТКИ ---
  {
    keyword: "orange",
    name: "Апельсиновый сок",
    category: "drink",
    kind: "veg",
    sizes: { small: 90, medium: 120, large: 150 },
    image: "./images/juice/1.jpg",
  },

  {
    keyword: "coffee",
    name: "Кофе",
    category: "drink",
    kind: "veg",
    sizes: { small: 100, medium: 130, large: 160 },
    image: "./images/juice/2.jpg",
  },
  {
    keyword: "milkshake",
    name: "Молочный коктейль",
    category: "drink",
    kind: "veg",
    sizes: { small: 150, medium: 180, large: 210 },
    image: "./images/juice/3.jpg",
  },
  {
    keyword: "carrot",
    name: "Морковный сок",
    category: "drink",
    kind: "veg",
    sizes: { small: 100, medium: 130, large: 160 },
    image: "./images/juice/4.jpg",
  },

  {
    keyword: "tea",
    name: "Чай",
    category: "drink",
    kind: "veg",
    sizes: { small: 80, medium: 100, large: 120 },
    image: "./images/juice/5.jpg",
  },
  {
    keyword: "apple",
    name: "Яблочный сок",
    category: "drink",
    kind: "veg",
    sizes: { small: 90, medium: 120, large: 150 },
    image: "./images/juice/6.jpg",
  },
];
